dae_solver:
  atol: 1.0e-8
  rtol: 1.0e-8
  start_time: 0.0
  stop_time: 1.9
  ncp: 500
  dae_specification_file: dae_examples/dae_specification_bouncing_balls_N7.yaml

optimizer:
  algorithm:
    type: "ADAM"  # "SGD" or "ADAM"
    params:
      step_size: 0.01
      # Adam-specific parameters (ignored for SGD):
      beta1: 0.9
      beta2: 0.999
      epsilon: 1.0e-8
  blend_sharpness: 300
  max_segments: 25
  downsample_segments: true # downsample each segment to max_points_per_segment
  max_points_per_segment: 25
  opt_params:
    - g
    - e_g
    - e_b
  max_iterations: 300
  tol: 1.0e-8
  print_every: 1
  max_blocks: 60 # 2N - 1 with margin
  max_targets: 600 # ~ 1.2 * ncp
generate_animation: false
