dae_solver:
  atol: 0.00001
  rtol: 0.00001
  start_time: 0.0
  stop_time: 2.0
  ncp: 400
  dae_specification_file: dae_examples/dae_specification_bouncing_ball.json
  
optimizer:
  discretization_method: bdf6  # backward_euler, trapezoidal, bdf2, bdf3, bdf4, bdf5, bdf6
  algorithm:
    type: "ADAM"  # "SGD" or "ADAM"
    params:
      step_size: 0.01
      # Adam-specific parameters (ignored for SGD):
      beta1: 0.9
      beta2: 0.999
      epsilon: 1.0e-8
  blend_sharpness: 250
  prediction_method: sigmoid  # 'sigmoid', 'linear', or 'hermite'
  max_segments: 3
  max_points_per_segment: 200
  opt_params:
    - g
    - e
  loss_type: mean
  max_iterations: 600
  tol: 1.0e-8
  print_every: 10
  device: cpu
  gpu_memory_fraction: 0.9


