dae_solver:
  atol: 0.0001
  rtol: 0.0001
  start_time: 0.0
  stop_time: 150.0
  ncp: 6000
  dae_specification_file: dae_examples/dae_specification_smooth.json
  
optimizer:
  step_size: 0.001
  opt_params:
    - C1_C
    - C2_C
    - C3_C
    - C4_C
    - C5_C
    - L1_L
    - L2_L
  max_iterations: 20
  tol: 0.001
  max_iterations_krylov: 30
  tol_krylov: 0.0001
  print_every: 20
  device: gpu
  gpu_memory_fraction: 0.9
  sequential_fallback:
    enable: False
    threshold: 500


