"""
Forward simulation of the N-ball bouncing-balls DAE using the PyTorch
event-driven simulator (`src.pytorch.bouncing_balls_n.BouncingBallsNModel`),
and side-by-side comparison against the IDA-based DAESolver from
`src.run.simulate_jax_bouncing_balls_N`.

Both simulators consume the same YAML config + DAE spec generated by
`src.run.modelica_balls_to_yaml`, so any differences in the trajectories
reflect numerical/event-handling differences between the two solvers --
not a difference in the model.
"""

from __future__ import annotations

import os
import sys
import time
from time import perf_counter

import numpy as np
import torch
import yaml

torch.set_default_dtype(torch.float64)

# Path setup
current_dir = os.path.dirname(os.path.abspath(__file__))
root_dir = os.path.dirname(os.path.dirname(current_dir))
sys.path.append(root_dir)
sys.path.append(os.path.join(root_dir, "src"))

from src.pytorch.bouncing_balls_n import BouncingBallsNModel  # noqa: E402
from src.run.simulate_jax_bouncing_balls_N import (  # noqa: E402
    simulate as simulate_ida,
)


def _load_spec_and_config(config_path: str):
    """Load the run config and the DAE spec it points to (YAML or JSON)."""
    with open(config_path, "r") as f:
        cfg = yaml.safe_load(f)
    solver_cfg = cfg["dae_solver"]
    spec_path = solver_cfg["dae_specification_file"]
    if not os.path.isabs(spec_path):
        spec_path = os.path.join(root_dir, spec_path)
    with open(spec_path, "r") as f:
        dae_data = yaml.safe_load(f)
    return cfg, dae_data, solver_cfg


def simulate_pytorch(config_path: str):
    """Run the PyTorch event-driven simulation. Returns (times, traj, dae_data)."""
    cfg, dae_data, solver_cfg = _load_spec_and_config(config_path)

    state_names = [s["name"] for s in dae_data["states"]]
    initial_state = [float(s["start"]) for s in dae_data["states"]]
    n_balls = sum(1 for n in state_names if n.startswith("x") and n[1:].isdigit())
    if 4 * n_balls != len(state_names):
        raise ValueError(
            f"State layout mismatch: counted {n_balls} balls but {len(state_names)} states."
        )

    p = {pp["name"]: float(pp["value"]) for pp in dae_data["parameters"]}
    t_start = float(solver_cfg["start_time"])
    t_stop = float(solver_cfg["stop_time"])
    ncp = int(solver_cfg["ncp"])

    if t_start != 0.0:
        # The PyTorch model assumes t0 = 0. Shift the time axis on output.
        pass

    model = BouncingBallsNModel(
        N=n_balls,
        g=p["g"], e_g=p["e_g"], e_b=p["e_b"], d_sq=p["d_sq"],
        x_min=p["x_min"], x_max=p["x_max"], y_min=p["y_min"], y_max=p["y_max"],
        initial_state=initial_state, adjoint=False,
    )

    print(f"[pytorch] N={n_balls}  states={4*n_balls}  events={model.n_events} "
          f"(walls={model.n_wall_events}, pairs={model.n_pair_events})")
    t0 = time.time()
    with torch.no_grad():
        times_t, traj_t, events = model.simulate_fixed_grid(
            t_end=t_stop - t_start, n_points=ncp, max_events=400,
            zeno_dt_threshold=1.0e-9, verbose=True,
        )
    elapsed = time.time() - t0

    times = times_t.cpu().numpy() + t_start
    traj = traj_t.cpu().numpy()
    print(f"[pytorch] simulated [{t_start}, {t_stop}] in {elapsed:.2f}s  "
          f"(events={len(events)}, points={len(times)})")
    return times, traj, dae_data, events


def _interp_states(t_query: np.ndarray, t_src: np.ndarray, x_src: np.ndarray) -> np.ndarray:
    """Per-state linear interpolation. t_query and t_src must be 1D and sorted."""
    out = np.empty((len(t_query), x_src.shape[1]), dtype=x_src.dtype)
    # np.interp handles out-of-range by clamping to endpoints
    for i in range(x_src.shape[1]):
        out[:, i] = np.interp(t_query, t_src, x_src[:, i])
    return out


def compare_and_plot(config_path: str, output_dir: str) -> None:
    # --- Run both simulators (wall-clock measured around each call) ---
    print("=" * 70)
    print("Running IDA (DAESolver) ...")
    print("=" * 70)
    t0 = perf_counter()
    times_ida, traj_ida, dae_data, _solver_cfg, events_ida = simulate_ida(config_path)
    elapsed_ida = perf_counter() - t0

    print("\n" + "=" * 70)
    print("Running PyTorch (BouncingBallsNModel) ...")
    print("=" * 70)
    t0 = perf_counter()
    times_pt, traj_pt, _, events_pt = simulate_pytorch(config_path)
    elapsed_pt = perf_counter() - t0

    # --- Numeric comparison on a common grid (intersection of time spans) ---
    t_lo = max(float(times_ida[0]), float(times_pt[0]))
    t_hi = min(float(times_ida[-1]), float(times_pt[-1]))
    rmse_pos = max_abs_pos = float("nan")
    n_cmp = 0
    if t_hi > t_lo:
        n_cmp = 1000
        t_cmp = np.linspace(t_lo, t_hi, n_cmp)
        ida_on_cmp = _interp_states(t_cmp, times_ida, traj_ida)
        pt_on_cmp = _interp_states(t_cmp, times_pt, traj_pt)

        state_names = [s["name"] for s in dae_data["states"]]
        n_balls = sum(1 for n in state_names if n.startswith("x") and n[1:].isdigit())
        pos_idx = []
        for i in range(1, n_balls + 1):
            pos_idx.append(state_names.index(f"x{i}"))
            pos_idx.append(state_names.index(f"y{i}"))

        diff_pos = ida_on_cmp[:, pos_idx] - pt_on_cmp[:, pos_idx]
        rmse_pos = float(np.sqrt(np.mean(diff_pos ** 2)))
        max_abs_pos = float(np.max(np.abs(diff_pos)))

    # --- Summary table -----------------------------------------------------
    n_states = traj_ida.shape[1]
    speedup = (elapsed_pt / elapsed_ida) if elapsed_ida > 0 else float("nan")
    print("\n" + "=" * 70)
    print(f"{'Comparison summary':^70s}")
    print("=" * 70)
    print(f"  {'metric':<22s} | {'IDA':>20s} | {'PyTorch':>20s}")
    print("  " + "-" * 67)
    print(f"  {'wall time [s]':<22s} | {elapsed_ida:>20.3f} | {elapsed_pt:>20.3f}")
    print(f"  {'output points':<22s} | {len(times_ida):>20d} | {len(times_pt):>20d}")
    print(f"  {'simulated to t [s]':<22s} | {float(times_ida[-1]):>20.4f} | {float(times_pt[-1]):>20.4f}")
    print(f"  {'events fired':<22s} | {len(events_ida):>20d} | {len(events_pt):>20d}")
    print(f"  PyTorch / IDA wall-time ratio = {speedup:.2f}x")
    if n_cmp > 0:
        print(f"\n  Position-state agreement on common interval "
              f"[{t_lo:.4f}, {t_hi:.4f}] s "
              f"(N={n_cmp}, {n_states} states):")
        print(f"    RMSE    = {rmse_pos:.6e}")
        print(f"    max-abs = {max_abs_pos:.6e}")
    print("=" * 70)

    # --- Plots ---
    os.makedirs(output_dir, exist_ok=True)
    _plot_xy_overlay(times_ida, traj_ida, times_pt, traj_pt, dae_data,
                     os.path.join(output_dir, "compare_ida_vs_pytorch_xy.png"))
    _plot_y_timeseries_overlay(times_ida, traj_ida, times_pt, traj_pt, dae_data,
                               os.path.join(output_dir, "compare_ida_vs_pytorch_yt.png"))


# ------------------------------------------------------------------ #
# Plotting
# ------------------------------------------------------------------ #
def _plot_xy_overlay(times_a, traj_a, times_b, traj_b, dae_data, output_path):
    import matplotlib.pyplot as plt
    from matplotlib import colormaps

    state_names = [s["name"] for s in dae_data["states"]]
    n_balls = sum(1 for n in state_names if n.startswith("x") and n[1:].isdigit())
    p = {pp["name"]: pp["value"] for pp in dae_data["parameters"]}
    cmap = colormaps.get_cmap("hsv").resampled(n_balls)

    fig, ax = plt.subplots(figsize=(9, 9))
    for i in range(1, n_balls + 1):
        xi = state_names.index(f"x{i}")
        yi = state_names.index(f"y{i}")
        c = cmap(i - 1)
        ax.plot(traj_a[:, xi], traj_a[:, yi], "-", color=c, alpha=0.65,
                linewidth=1.0, label=f"IDA B{i}" if i == 1 else None)
        ax.plot(traj_b[:, xi], traj_b[:, yi], "--", color=c, alpha=0.65,
                linewidth=1.0, label=f"PyTorch B{i}" if i == 1 else None)
        ax.plot(traj_a[0, xi], traj_a[0, yi], "o", color=c, markersize=5,
                markeredgecolor="k", markeredgewidth=0.5)

    ax.plot([p["x_min"], p["x_max"], p["x_max"], p["x_min"], p["x_min"]],
            [p["y_min"], p["y_min"], p["y_max"], p["y_max"], p["y_min"]],
            "k--", alpha=0.4, linewidth=1)
    pad = 0.05 * max(p["x_max"] - p["x_min"], p["y_max"] - p["y_min"])
    ax.set_xlim(p["x_min"] - pad, p["x_max"] + pad)
    ax.set_ylim(p["y_min"] - pad, p["y_max"] + pad)
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel("x position")
    ax.set_ylabel("y position")
    ax.set_title(
        f"{n_balls}-ball trajectories: IDA (solid) vs PyTorch (dashed)"
    )
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper right", fontsize=9)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close(fig)
    print(f"Plot saved to: {output_path}")


def _plot_y_timeseries_overlay(times_a, traj_a, times_b, traj_b, dae_data, output_path):
    import matplotlib.pyplot as plt
    from matplotlib import colormaps

    state_names = [s["name"] for s in dae_data["states"]]
    n_balls = sum(1 for n in state_names if n.startswith("x") and n[1:].isdigit())
    p = {pp["name"]: pp["value"] for pp in dae_data["parameters"]}
    cmap = colormaps.get_cmap("hsv").resampled(n_balls)

    fig, (ax_x, ax_y) = plt.subplots(2, 1, figsize=(14, 9), sharex=True)

    for i in range(1, n_balls + 1):
        xi = state_names.index(f"x{i}")
        yi = state_names.index(f"y{i}")
        c = cmap(i - 1)
        ax_x.plot(times_a, traj_a[:, xi], "-",  color=c, alpha=0.7, linewidth=0.9,
                  label=f"IDA B{i}" if i == 1 else None)
        ax_x.plot(times_b, traj_b[:, xi], "--", color=c, alpha=0.7, linewidth=0.9,
                  label=f"PyTorch B{i}" if i == 1 else None)
        ax_y.plot(times_a, traj_a[:, yi], "-",  color=c, alpha=0.7, linewidth=0.9)
        ax_y.plot(times_b, traj_b[:, yi], "--", color=c, alpha=0.7, linewidth=0.9)

    for ref in (p["y_min"], p["y_max"]):
        ax_y.axhline(ref, color="k", linestyle=":", alpha=0.4)
    for ref in (p["x_min"], p["x_max"]):
        ax_x.axhline(ref, color="k", linestyle=":", alpha=0.4)

    ax_x.set_ylabel("x position")
    ax_x.set_title(f"x(t) and y(t) — IDA (solid) vs PyTorch (dashed)  "
                   f"({n_balls} balls)")
    ax_x.grid(True, alpha=0.3)
    ax_x.legend(loc="upper right", fontsize=9)

    ax_y.set_xlabel("time [s]")
    ax_y.set_ylabel("y position")
    ax_y.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close(fig)
    print(f"Plot saved to: {output_path}")


def main():
    config_path = os.path.join(root_dir, "config", "config_bouncing_balls_N25.yaml")
    output_dir = os.path.join(root_dir, "results")
    compare_and_plot(config_path, output_dir)


if __name__ == "__main__":
    main()
